# Generated by Django 5.2.6 on 2025-09-15 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='proposal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='proposals.proposal'),
        ),
    ]
