version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_password
    ports:
      - "5433:5432"

  web:
    build: .
    volumes:
      - .:/app
      - static_volume:/NEW PROJECT/FreelancerM/staticfiles_collected
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://django_user:django_password@db:5432/django_db
      PYTHONPATH: /app/FreelancerM

volumes:
  postgres_data:
  static_volume:
