# Generated by Django 5.2.6 on 2025-09-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='is_read_by_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposal',
            name='is_read_by_freelancer',
            field=models.BooleanField(default=False),
        ),
    ]
