# Generated by Django 5.2.6 on 2025-09-17 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_category'),
        ('messaging', '0003_message_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='jobs.job'),
        ),
    ]
