# Generated by Django 5.2.6 on 2025-09-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_alter_message_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
